name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports: ["33306:3306"]
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v4

    # ── Client ─────────────────────────────────────────────
    - name: Setup Node
      uses: actions/setup-node@v4
      with: { node-version: 20 }
    - name: Install client deps
      run: |
        cd client
        npm ci
    - name: Lint & test client
      run: |
        cd client
        npm run lint
        npm test -- --run

    # ── Server ─────────────────────────────────────────────
    - uses: actions/setup-go@v5
      with: { go-version: '1.22' }
    - name: Test server
      run: |
        cd server
        go vet ./...
        go test ./...

    # ── Docker build (cache only) ─────────────────────────
    - name: Build images
      run: docker build -f deployments/Dockerfile.api -t api:ci .
